[package]
name = "pulsar-client-demo"
version = "0.1.0"
authors = ["fish <liangyuanpengem@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.23"
pulsar = "0.3.0"
tokio = "0.1.11"